spring:
  cloud:
    gateway:
      routes:
      - id: fornecedor_route
        predicates:
        - Path=/fornecedor/**
        uri: "http://localhost:8081"
      - id: transportador_route
        predicates:
        - Path=/transportador/**
        uri: "http://localhost:8083"
      - id: loja_route
        predicates:
        - Path=/loja/**
        uri: "http://localhost:8080"
      - id: carro_route
        predicates:
        - Path=/carro/**
        uri: "http://localhost:8080"
