management:
  endpoints:
    web:
      exposure:
        include: health, refresh

health:
  config:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: info

spring:
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        ########## Fornecedor
        - id: fornecedor
          uri: localhost:8081
          predicates:
            - Path=/fornecedor/**
