 zuul:
  routes:
    first:
      path: /fornecedor/**
      url: http://localhost:8081
    second:
      path: /loja/**
      url: http://localhost:8080
    third: 
      path: /transportador/**
      url: http://localhost:8083
