spring:
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        ########## Fornecedor
        - id: fornecedor
          uri: localhost:8081
          predicates:
            - Path=/fornecedor/**
